### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by ZeroDot1** [Aztorius/magicfountain#18]
See https://github.com/blog/2111-issue-and-pull-request-templates

# ISSUE_TEMPLATE.md
```
### Description:

*Replace this line with a brief summary of the problem.*

### Steps To Reproduce:

1.
2.
3.

### Log Files

- Use a service like http://paste2.org/ to provide links to the logs.


### Additional Informations:

- Operating System:
```
# PULL_REQUEST_TEMPLATE.md
```
Fixes #

## Proposed Changes

  -
  -
```

**Comment by Aztorius** [comment]
Done 381a0429f5f343b78b7b3117d8a72af0b5039e18

**Comment by ZeroDot1** [comment]
The templates are not displayed.

Please create a .github folder.
Move the templates to the .github directory
