### ISSUE TITLE
Internationalisation with transifex.com

### ISSUE THREAD

**Issue by ZeroDot1** [Aztorius/magicfountain#2]
To make it possible to make the MagicFountain available in more languages.
https://www.transifex.com/

**Comment by Aztorius** [comment]
I'll do it. Hopefully very soon.

**Comment by ZeroDot1** [comment]
I will then make the translation in German.

**Comment by Aztorius** [comment]
I think I will use Zanata instead of Transifex, it's a bit more straightforward for open source project to register.

**Comment by ZeroDot1** [comment]
OK, I have an account at Zanata, and can also translate.

**Comment by Aztorius** [comment]
Well, finally it works with Transifex so : https://www.transifex.com/magicfountain/magicfountain/dashboard/

**Comment by ZeroDot1** [comment]
The translation is ready you can pull fom transifex.

**Comment by ZeroDot1** [comment]
Please add new strings for language.
Photo:
![_dsc0014](https://user-images.githubusercontent.com/28985171/29670045-c22f0034-88e5-11e7-8812-0131f2d8b6e1.jpg)

**Comment by Aztorius** [comment]
You mean replace en with English ?

**Comment by ZeroDot1** [comment]
Yes, exactly, and language with language [Sprache/Deutsch/Englisch/Fanzösisch], in different languages.

**Comment by ZeroDot1** [comment]
The translation is ready you can pull fom transifex.

**Comment by Aztorius** [comment]
Done

**Comment by ZeroDot1** [comment]
It works, thanks for the quick update, :)
