### ISSUE TITLE
Make Open Save and Print dialogs translatable

### ISSUE THREAD

**Issue by ZeroDot1** [Aztorius/magicfountain#23]
Screenshots:
![bildschirmfoto_2017-08-25_22-06-51](https://user-images.githubusercontent.com/28985171/29730801-205c74d2-89e2-11e7-8b8f-b7ba48a35059.png)
![bildschirmfoto_2017-08-25_22-07-25](https://user-images.githubusercontent.com/28985171/29730802-20691214-89e2-11e7-8947-86c13472cc1f.png)
![bildschirmfoto_2017-08-25_22-08-00](https://user-images.githubusercontent.com/28985171/29730803-206b76c6-89e2-11e7-9891-d349484ccba2.png)

**Comment by Aztorius** [comment]
With KDE on Fedora : Open and Save dialogs are translated by Qt (it's Qt default dialogs for both).
Only the print dialog is not translated.

**Comment by Aztorius** [comment]
By default, Qt will try to open default system dialog for opening files or print, so the system language is use. I'm trying to set the language in the other case.

**Comment by ZeroDot1** [comment]
It works, thanks for the quick update, :)
