### ISSUE TITLE
A website for Magic Fountain

### ISSUE THREAD

**Issue by ZeroDot1** [Aztorius/magicfountain#27]
I have created a simple web page for the project. 
URL: http://magicfountain.pytalhost.info/
Is this ok or should something be changed?

**Comment by Aztorius** [comment]
It's ok, but it should be easier to host on GitHub i think ?

**Comment by ZeroDot1** [comment]
See: https://pages.github.com/
No problem, here is the source code: 
[index.html.tar.gz](https://github.com/Aztorius/magicfountain/files/1253725/index.html.tar.gz)

EDIT: 
If the page on GitHub is, I delete it from the other service provider.

**Comment by Aztorius** [comment]
https://aztorius.github.io/magicfountain/

**Comment by ZeroDot1** [comment]
I've added an update for the css style.
https://github.com/Aztorius/magicfountain/pull/28/commits/cf92f2ccc25f15c4fc998641ecdacd06cb4bfaae

**Comment by ZeroDot1** [comment]
I've added an update for the page.
https://github.com/Aztorius/magicfountain/pull/34

**Comment by ZeroDot1** [comment]
I want to create the page in different languages, is this OK?
I would like the program to be very understandable, and everyone can handle it, so I thought that would be useful when the page is in the same languages as the program.
Screenshot:
![bildschirmfoto_2017-08-27_23-24-20](https://user-images.githubusercontent.com/28985171/29754174-427f24d4-8b80-11e7-8276-fd2a862cbd2c.png)
### Language menu code:
```html
  <a href="index.html"><img align="middle" id="blinker" src="flags/en.svg" title="Language = English" alt="English" width="24" height="24"><img/></a>
    <a href="index_de.html"><img align="middle" src="flags/de.svg" title="Sprache = Deutsch" alt="Deutsch" width="22" height="22"><img/></a>
    <a href="index_fr.html"><img align="middle" src="flags/fr.svg" title="Langue = Français" alt="Français" width="22" height="22"><img/></a>
```

**Comment by Aztorius** [comment]
It's ok. No problem.
