### ISSUE TITLE
Magic Fountain on Ubuntu 17.04 the menu is not displayed

### ISSUE THREAD

**Issue by ZeroDot1** [Aztorius/magicfountain#46]
I have tested Magic Fountain with Ubuntu 17.04.
The. deb version 1.0.0.0 Alpha 6 package has been used for testing.

Before installing Magic Fountain, the following packages must be installed.

`sudo apt-get install libdrm-dev libegl1-mesa-dev libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libmirclient-dev libmircommon-dev libmircookie-dev libmircore-dev libprotobuf-dev libpthread-stubs0-dev libqt5opengl5-dev libwayland-bin libwayland-dev libx11-dev libx11-doc libx11-xcb-dev libxau-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxkbcommon-dev libxshmfence-dev libxxf86vm-dev mesa-common-dev qt5-default qt5-qmake qtbase5-dev qtbase5-dev-tools x11proto-core-dev x11proto-damage-dev x11proto-dri2-dev x11proto-fixes-dev x11proto-gl-dev x11proto-input-dev x11proto-kb-dev x11proto-xext-dev x11proto-xf86vidmode-dev xorg-sgml-doctools xtrans-dev zlib1g-dev`

The menu is not displayed.
Photo: 
![_dsc0079](https://user-images.githubusercontent.com/28985171/29983106-a55e6eac-8f54-11e7-94c9-66fc2140cd9e.jpg)

**Comment by Aztorius** [comment]
In Unity the menu is displayed at the top of the screen, so this is the normal behaviour.
That's a lot of dependencies. I will look into that.

**Comment by ZeroDot1** [comment]
OK thanks, I've never used Ubuntu actively before.
