### ISSUE TITLE
Update homepage???

### ISSUE THREAD

**Issue by ZeroDot1** [Aztorius/magicfountain#49]
I haven't heard about the project for a long time, so I wanted to ask if I should update the homepage, because there have been some changes.

**Comment by Aztorius** [comment]
You can update the homepage.
I just have less time to work on the project.

**Comment by ZeroDot1** [comment]
OK, thanks for informing me, I will make an update as soon as possible.

**Comment by ZeroDot1** [comment]
Done!

Homepage Update: Version 3.5 Date 21.10.2017 13:47: See #50

**Comment by ZeroDot1** [comment]
@Aztorius In the next days I will update the homepage.

**Comment by Aztorius** [comment]
Noted
